
export const AuditEventActions = {
    TASK_CREATED: "TASK_CREATED",
    TASK_TITLE_CHANGED: "TASK_TITLE_CHANGED",
    TASK_DESCRIPTION_CHANGED: "TASK_DESCRIPTION_CHANGED",
    TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
    TASK_DELETED: "TASK_DELETED",

    ORG_MEMBER_HIRED: "ORG_MEMBER_HIRED",
    ORG_MEMBER_FIRED: "ORG_MEMBER_FIRED",
    ORG_MEMBER_ROLE_CHANGED: "ORG_MEMBER_ROLE_CHANGED",

    MEMBER_COMPLETED_TASK: "MEMBER_COMPLETED_TASK",
    MEMBER_CANCELED_TASK: "MEMBER_CANCELED_TASK",
} as const;

export type AuditEventAction = typeof AuditEventActions[keyof typeof AuditEventActions];