/** Matches backend AuditEventActions */
export const AUDIT_ACTIONS = [
  'TASK_CREATED',
  'TASK_TITLE_CHANGED',
  'TASK_DESCRIPTION_CHANGED',
  'TASK_STATUS_CHANGED',
  'TASK_DELETED',
  'ORG_MEMBER_HIRED',
  'ORG_MEMBER_FIRED',
  'ORG_MEMBER_ROLE_CHANGED',
  'MEMBER_COMPLETED_TASK',
  'MEMBER_CANCELED_TASK',
  'GET_AUDIT_EVENT',
  'GET_AUDIT_EVENTS_FILTERED',
  'ORGANIZATION_CREATED',
  'ORGANIZATION_RENAMED',
  'LIST_ALL_MEMBERS',
  'INVITATION_CREATED',
  'INVITATION_ACCEPTED',
  'INVITATION_REJECTED',
  'INVITATION_CANCELED',
  'ORGANIZATION_VIEWED',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
